name: chatapp
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1  # Correctly indented
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6  # Correctly placed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/ # Ensure your image files are in the correct directory
